name: Dist

on:
  push:
    branches: [main]

jobs:
  dist:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v1
        with:
          version: 11
          runtime: node@24
          cache: true

      - name: Install dependencies
        run: pnpm install

      - name: build dist
        run: pnpm build

      - name: Prepare dist branch
        run: cp README.md dist/

      - name: Push dist branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: dist
          git-config-name: Isla
          git-config-email: bot@nn.ci
          commit-message: "chore: build dist script"