name: Dist

on:
  push:
    branches: [main]

jobs:
  dist:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6

      - name: Setup Node.js environment
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install dependencies
        run: pnpm install

      - name: build dist
        run: pnpm build
        
      - name: Add, Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: build dist script"
          commit_user_name: Isla
          commit_user_email: bot@nn.ci
          commit_author: "Isla <bot@nn.ci>"